name: Kross post github actions
on:
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: create env file
      #   run: |
      #     touch .env
      #     echo DEV_TO_API=${{ secrets.DEV_TO_API_KEY }} >> .env
      # - run: npm install
      # - run: npm run build --if-present
      # - run: node index.js
